### PR TITLE
deps: latest @helia/verified-fetch & http range support testing

### PR DESCRIPTION
**Pull request by SgtPooki**
## Title

This PR is WIP utilizing the latest release of `@helia/verified-fetch` with the http range header support.

## Description

This PR updates the service-worker-gateway to support range requests. The `@helia/verified-fetch` package has been updated to the latest release, which includes support for the range header.

## Notes & open questions

PR is ready for review. things are working.

~~PR is in draft mode while I test these things out, but for now, the only commit is updating the packages and resolving the conflicts.~~

- [x] Is there additional work to ensure the range header is passed through?
    - A simple fetch in the dev console can return singular characters for the "hello world" CID without worrying about any code changes.
- [x] can we load bigbuckbunny.mp4 with the range header? are they sent and received properly?
- [x] can we do a byte range request for an identity CID and get only a single first/last/middle character back? (e2e test)

### TODO:
- [ ] implement ascii.txt range request test using fixture at https://github.com/ipfs/gateway-conformance/blob/ed74b532fc7662732ec87d92c49435668369db66/tests/path_gateway_unixfs_test.go#L489C25-L489C34
- [ ] implement range request test using `file-3k-and-3-blocks-missing-block.car` from https://github.com/ipfs/gateway-conformance/blob/ed74b532fc7662732ec87d92c49435668369db66/tests/trustless_gateway_car_test.go#L445

#### 2024-03-16 00:32 UTC

- Note: attempting two videos resulted in Brave rendering unusable video controls and video viewer, where no action did anything.
    - bigbuckbunny=`bafybeidsp6fva53dexzjycntiucts57ftecajcn5omzfgjx57pqfy3kwbq`
    - stockSkateboarder=`bafkreiezuss4xkt5gu256vjccx7vocoksxk77vwmdrpwoumfbbxcy2zowq`

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by SgtPooki** [comment]
it works in the terminal...

image

**Comment by SgtPooki** [comment]
related: https://googlechrome.github.io/samples/service-worker/prefetch-video/

**Comment by SgtPooki** [comment]
requesting http://bafkreiezuss4xkt5gu256vjccx7vocoksxk77vwmdrpwoumfbbxcy2zowq.ipfs.helia-sw-gateway.localhost/ does show that something is happening:

image

**Comment by SgtPooki** [comment]
For some reason, two requests are being sent, both are being logged in dev console, but service worker is only recognizing one, and the second one (for document) is stuck in pending...?

image

I'm testing the same content that is at https://storage.googleapis.com/media-session/sample.webm. Created cid with `curl https://storage.googleapis.com/media-session/sample.webm | npx kubo add --cid-version 1`

* https://bafybeid2sc4k5ynx5yo7wg23fzw2ni4xxuxi7kdq5q3lyurkvglh5wrwmi.ipfs.dweb.link/
* http://bafybeid2sc4k5ynx5yo7wg23fzw2ni4xxuxi7kdq5q3lyurkvglh5wrwmi.ipfs.helia-sw-gateway.localhost/

it works at dweb.link fine. 

### dweb.link response headers:

```
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Headers: Range
Access-Control-Allow-Headers: User-Agent
Access-Control-Allow-Headers: X-Requested-With
Access-Control-Allow-Methods: GET
Access-Control-Allow-Methods: HEAD
Access-Control-Allow-Methods: OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length
Access-Control-Expose-Headers: Content-Range
Access-Control-Expose-Headers: X-Chunked-Output
Access-Control-Expose-Headers: X-Ipfs-Path
Access-Control-Expose-Headers: X-Ipfs-Roots
Access-Control-Expose-Headers: X-Stream-Output
Cache-Control: public, max-age=29030400, immutable
Content-Length: 83216545
Content-Range: bytes 0-83216544/83216545
Content-Type: video/webm
Date: Sat, 16 Mar 2024 02:33:53 GMT
Etag: "bafybeid2sc4k5ynx5yo7wg23fzw2ni4xxuxi7kdq5q3lyurkvglh5wrwmi"
Server: openresty
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Timing-Allow-Origin: *
X-Bfid: f7e1b7ae23ff2319d0efca362021b47b
X-Ipfs-Lb-Pop: gateway-bank2-sv15
X-Ipfs-Path: /ipfs/bafybeid2sc4k5ynx5yo7wg23fzw2ni4xxuxi7kdq5q3lyurkvglh5wrwmi/
X-Ipfs-Pop: ipfs-bank3-sv15
X-Ipfs-Roots: bafybeid2sc4k5ynx5yo7wg23fzw2ni4xxuxi7kdq5q3lyurkvglh5wrwmi
X-Proxy-Cache: MISS
```

### helia-sw-gateway.localhost response headers:

```
accept-ranges: bytes
cache-control: public, max-age=29030400, immutable
content-range: bytes 0-83216545/83216545
content-type: video/webm
etag: "bafybeid2sc4k5ynx5yo7wg23fzw2ni4xxuxi7kdq5q3lyurkvglh5wrwmi"
x-ipfs-path: ipfs://bafybeid2sc4k5ynx5yo7wg23fzw2ni4xxuxi7kdq5q3lyurkvglh5wrwmi/
x-ipfs-roots: bafybeid2sc4k5ynx5yo7wg23fzw2ni4xxuxi7kdq5q3lyurkvglh5wrwmi
```

**Comment by SgtPooki** [comment]
its working in firefox with [`448e104` (#122)](https://github.com/ipfs-shipyard/helia-service-worker-gateway/pull/122/commits/448e104abf96b4deeb7bab62ed552e510dddf706):

image


Brave is giving me some odd details in the network tab:

image


Maybe I need to restart my browser or try a private tab..

**Comment by SgtPooki** [comment]
the firefox headers look much different.. 
image

**Comment by SgtPooki** [comment]
chrome shows it broken in the same way, and safari is still the new IE:

image

**Comment by SgtPooki** [comment]
tried deploying to sw.sgtpooki.com and after confirming that the new service worker was loaded, it doesn't work there either (except the skateboarder stock video on FF)

- skateboarder stock video [small, working]: https://bafkreiezuss4xkt5gu256vjccx7vocoksxk77vwmdrpwoumfbbxcy2zowq.ipfs.sw.sgtpooki.com/
- sample.webm from https://googlechrome.github.io/samples/service-worker/prefetch-video/ example [medium, broken]: https://bafybeid2sc4k5ynx5yo7wg23fzw2ni4xxuxi7kdq5q3lyurkvglh5wrwmi.ipfs.sw.sgtpooki.com/
- bigbuckbunny [big, broken]: https://bafybeidsp6fva53dexzjycntiucts57ftecajcn5omzfgjx57pqfy3kwbq.ipfs.sw.sgtpooki.com/

**Comment by SgtPooki** [comment]
ok they're not working when deployed. the skateboarder was a super old cached version of helia-service-worker-gateway.

I updated it, and it's also not working.

**Comment by SgtPooki** [comment]
So, I stood up a simple nodejs server for serving the sample.webm to see what the browser is actually sending and put the results at https://gist.github.com/SgtPooki/9efc039d1d349d112d0f505b2ed275c8

I wasn't planning on targeting Safari at all, but I won't be pursuing safari any further with helia-service-worker-gateway due to it not even working well with this basic case.

**Comment by SgtPooki** [comment]
I just created https://gist.github.com/SgtPooki/9efc039d1d349d112d0f505b2ed275c8#file-demo-video-server-vfetch-js which can be used to reproduce the service worker error in an easier way.

**Comment by SgtPooki** [comment]
i think i got it. byte range is returning invalid byte string. i’ve been testing with bafybeid2sc4k5ynx5yo7wg23fzw2ni4xxuxi7kdq5q3lyurkvglh5wrwmi and hardcoding headers.. and got it fixed with the below

```js
  if (headers['content-range'] === 'bytes 0-83216545/83216545') {
    headers['content-range'] = 'bytes 0-83216544/83216545'
  }
```

**Comment by SgtPooki** [comment]
http://helia-sw-gateway.localhost/ipfs/bafybeid2sc4k5ynx5yo7wg23fzw2ni4xxuxi7kdq5q3lyurkvglh5wrwmi

is working in brave with the latest from https://github.com/ipfs/helia-verified-fetch/pull/24

**Comment by SgtPooki** [comment]
image

**Review by SgtPooki — COMMENTED** [review]
self review

**Comment by SgtPooki** [comment]
one issue that comes up when loading large videos (https://bafybeidsp6fva53dexzjycntiucts57ftecajcn5omzfgjx57pqfy3kwbq.ipfs.sw.sgtpooki.com/) is that the request seems to take a while to return. I believe we're waiting for the full content to be loaded, when instead, we should return quickly with minimal data.. 

I thought we would see a second request from the browser when it sees the content type, but the browser is waiting until the entire first response is done before it sends any additional requests. We can't cancel/abort the original request until the browser tells us to do so, because someone may want the entire content.

Opened https://github.com/ipfs-shipyard/helia-service-worker-gateway/issues/131 for this

**Comment by 2color** [comment]
> one issue that comes up when loading large videos (https://bafybeidsp6fva53dexzjycntiucts57ftecajcn5omzfgjx57pqfy3kwbq.ipfs.sw.sgtpooki.com/) is that the request seems to take a while to return.

Are you referring to the `verifiedFetch` request from the SW?

**Comment by 2color** [comment]
Btw, after the initial loading of https://bafybeidsp6fva53dexzjycntiucts57ftecajcn5omzfgjx57pqfy3kwbq.ipfs.sw.sgtpooki.com/ I'm getting a 502 that is coming from the service worker. 
Screenshot 2024-03-19 at 2 48 31 pm


If I attempt to load the config page I also get a 502: https://bafybeidsp6fva53dexzjycntiucts57ftecajcn5omzfgjx57pqfy3kwbq.ipfs.sw.sgtpooki.com/#ipfs-sw-config

**Comment by SgtPooki** [comment]
> > one issue that comes up when loading large videos ([bafybeidsp6fva53dexzjycntiucts57ftecajcn5omzfgjx57pqfy3kwbq.ipfs.sw.sgtpooki.com](https://bafybeidsp6fva53dexzjycntiucts57ftecajcn5omzfgjx57pqfy3kwbq.ipfs.sw.sgtpooki.com/)) is that the request seems to take a while to return.
> 
> Are you referring to the `verifiedFetch` request from the SW?

Yea, the first time verified fetch is called for the content, it loads 



> Btw, after the initial loading of [bafybeidsp6fva53dexzjycntiucts57ftecajcn5omzfgjx57pqfy3kwbq.ipfs.sw.sgtpooki.com](https://bafybeidsp6fva53dexzjycntiucts57ftecajcn5omzfgjx57pqfy3kwbq.ipfs.sw.sgtpooki.com/) I'm getting a 502 that is coming from the service worker. 
> 
> If I attempt to load the config page I also get a 502: [bafybeidsp6fva53dexzjycntiucts57ftecajcn5omzfgjx57pqfy3kwbq.ipfs.sw.sgtpooki.com/#ipfs-sw-config](https://bafybeidsp6fva53dexzjycntiucts57ftecajcn5omzfgjx57pqfy3kwbq.ipfs.sw.sgtpooki.com/#ipfs-sw-config)

Which service worker is registered? When i load https://bafybeidsp6fva53dexzjycntiucts57ftecajcn5omzfgjx57pqfy3kwbq.ipfs.sw.sgtpooki.com/#ipfs-sw-config, and reload, it continues displaying the config page for me, so i think you may have an old SW registered?

**Comment by lidel** [comment]
Found DoH bug, filled https://github.com/ipfs/helia/issues/474 (not a blocker, just fyi)

**Comment by SgtPooki** [comment]
FYI: merging this in order to continue improvements moving forward. will work on #134 next

**Pull request merged**
